-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 21:00:00 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema prj_local
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `project` ;

CREATE TABLE IF NOT EXISTS `project` (
  `project_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`project_id`),
  UNIQUE INDEX `unq_project_name` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10000000
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `aud_project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aud_project` ;

CREATE TABLE IF NOT EXISTS `aud_project` (
  `project_id` BIGINT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  `action` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`project_id`, `timestamp`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DELIMITER +

DROP TRIGGER IF EXISTS `project_BEFORE_DELETE` +
CREATE TRIGGER `prj_local`.`project_BEFORE_DELETE` BEFORE DELETE ON `project` FOR EACH ROW
BEGIN
	INSERT INTO AUD_PROJECT (project_id, timestamp, action, name)
    VALUES (OLD.project_id, NOW(), 'delete', OLD.name);
END+


DROP TRIGGER IF EXISTS `project_BEFORE_UPDATE` +
CREATE TRIGGER `prj_local`.`project_BEFORE_UPDATE` BEFORE UPDATE ON `project` FOR EACH ROW
BEGIN
	INSERT INTO AUD_PROJECT (project_id, timestamp, action, name)
    VALUES (NEW.project_id, NOW(), 'update', NEW.name);
END+


DROP TRIGGER IF EXISTS `project_BEFORE_INSERT` +
CREATE TRIGGER `prj_local`.`project_BEFORE_INSERT` BEFORE INSERT ON `project` FOR EACH ROW
BEGIN
	INSERT INTO AUD_PROJECT (project_id, timestamp, action, name)
    VALUES (NEW.project_id, NOW(), 'create', NEW.name);
END+


DELIMITER ;
